---
dependencies:
  - role: rvm.ruby
    # TODO: How do we get it to use what's in the .ruby-version file?
    rvm1_rubies:
      - ruby-3.1.3
    # The stable release is almost two years old at this stage and doesn't
    # contain ruby 3.1 or 3.2. So we have to use head instead.
    rvm1_rvm_version: 'head'
    rvm1_install_flags: '--auto-dotfiles'      # Remove --user-install from defaults
    rvm1_install_path: /usr/local/rvm          # Set to system location
    rvm1_user: root                            # Need root account to access system location
    # Use round-robin pool of gpg key servers to avoid timeout
    rvm1_gpg_key_server: 'hkp://pool.sks-keyservers.net'
  - role: nickhammond.logrotate
    logrotate_scripts:
      - name: production
        path: "/srv/www/production/shared/log/*.log"
        options:
          - daily
          - rotate 30
          - compress
          - missingok
          - copytruncate
