# This is a test playbook for creating an ec2 instance for theyvoteforyou

# Run this like so:
# ansible-playbook -i ec2.py ec2-provisioning-test.yml

# Before running this, however, you will need to set the environment variables
# export AWS_ACCESS_KEY_ID='AK123'
# export AWS_SECRET_ACCESS_KEY='abc123'

# More local requirements:
# `sudo pip install --ignore-installed six boto3`
#

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Set up security group for theyvoteforyou
      ec2_group:
        name: theyvoteforyou
        description: theyvoteforyou security group
        region: 'ap-southeast-2'
        rules:
        - proto: tcp
          ports:
            - 22
            - 80
            - 443
          cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
        # Sydney
        region: 'ap-southeast-2'
        key_name: test
        group: theyvoteforyou
        instance_type: t2.micro
        # Ubuntu 16.04 in Sydney
        image: "ami-974eb0f5"
        wait: true
        count_tag:
          Name: theyvoteforyou
        exact_count: 1
        instance_tags:
          Name: theyvoteforyou
      register: ec2

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups:
          - tag_Name_theyvoteforyou
          - ec2
      with_items: "{{ ec2.instances }}"

- hosts: tag_Name_theyvoteforyou
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

# TODO: Don't want to run dns update stuff
- hosts: tag_Name_theyvoteforyou
  become: true
  roles:
    - theyvoteforyou
  vars_files:
    - encrypted_vars/theyvoteforyou.yml
