# This is a test playbook for configuring an ec2 instance for theyvoteforyou

# Run this like so:
# ansible-playbook -i ec2-hosts ec2-provisioning-test.yml

# Use terraform (see terraform directory) to actually provision ec2 infrastructure

- hosts: theyvoteforyou
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

- hosts: theyvoteforyou
  become: true
  tasks:
    - name: Get information about the RDS instance
      rds:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        command: facts
        instance_name: main-database
        region: "{{ ec2_region }}"
      register: rds

    - name: Create theyvoteforyou database on RDS instance
      mysql_db:
        login_host: "{{ rds.instance.endpoint }}"
        login_user: admin
        login_password: "{{ rds_admin_password }}"
        name: theyvoteforyou

    - name: Create a theyvoteforyou user with access to the database
      mysql_user:
        login_host: "{{ rds.instance.endpoint }}"
        login_user: admin
        login_password: "{{ rds_admin_password }}"
        name: theyvoteforyou
        password: "{{ theyvoteforyou_mysql_password }}"
        priv: 'theyvoteforyou.*:ALL'

    - name: Install nginx (for the benefit of certbot)
      apt: pkg=nginx

# This needs to run after the two DNS entries for the hosts are added
# It also needs to be run after nginx has been installed
# And it depends on the deploy user being created
- hosts: theyvoteforyou
  become: true
  vars:
    certbot_auto_renew_user: deploy
    certbot_auto_renew_minute: 10
    certbot_auto_renew_hour: 7
    certbot_create_if_missing: yes
    certbot_certs:
      # TODO: Update the domains that we'll be generating the certificate for
      # In production they should be at least:
      # theyvoteforyou.org.au
      # www.theyvoteforyou.org.au
      # theyvoteforyou.org
      # www.theyvoteforyou.org
      # theyvoteforyou.com.au
      # www.theyvoteforyou.com.au
      - email: contact@oaf.org.au
        domains:
          - "{{ theyvoteforyou_domain }}"
          - www."{{ theyvoteforyou_domain }}"
      - email: contact@oaf.org.au
        domains:
          - "test.{{ theyvoteforyou_domain }}"
          - "www.test.{{ theyvoteforyou_domain }}"
    github_users: []
  roles:
    - deploy-user
    - geerlingguy.certbot

# TODO: Don't want to run dns update stuff
- hosts: theyvoteforyou
  become: true
  roles:
    - theyvoteforyou
  vars_files:
    - encrypted_vars/theyvoteforyou.yml
