# This is a test playbook for creating an ec2 instance for theyvoteforyou

# Run this like so:
# ansible-playbook -i ec2.py ec2-provisioning-test.yml

# Before running this, however, you will need to set the environment variables
# export AWS_ACCESS_KEY_ID='AK123'
# export AWS_SECRET_ACCESS_KEY='abc123'

# More local requirements:
# `sudo pip install --ignore-installed six boto3`
#

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Set up security group for theyvoteforyou
      ec2_group:
        name: theyvoteforyou
        description: theyvoteforyou security group
        region: 'ap-southeast-2'
        rules:
        - proto: tcp
          ports:
            - 22
            - 80
            - 443
          cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
        # Sydney
        region: 'ap-southeast-2'
        key_name: test
        group: theyvoteforyou
        # t2.micro doesn't give us enough memory
        instance_type: t2.small
        # Ubuntu 16.04 in Sydney
        image: "ami-974eb0f5"
        wait: true
        count_tag:
          Name: theyvoteforyou
        exact_count: 1
        instance_tags:
          Name: theyvoteforyou
      register: ec2

    # For this to work we need to have allocated one of these
    # and we need to update the ip address that's used here
    - name: Allocate one of our elastic IPs to the instance
      ec2_eip:
        device_id: "{{ ec2.tagged_instances[0].id }}"
        ip: 13.211.24.93
        region: 'ap-southeast-2'

    - name: Add all instance public IPs to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups:
          - tag_Name_theyvoteforyou
          - ec2
      with_items: "{{ ec2.instances }}"

- hosts: tag_Name_theyvoteforyou
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: False

- hosts: tag_Name_theyvoteforyou
  become: true
  tasks:
    # Run this from the machine in question so we easy access to its address
    # Only run this if this is running on an EC2 instance
    # TODO: Move this to the theyvoteforyou role
    - name: Setup DNS for ec2.theyvoteforyou.org.au
      dnsmadeeasy:
        account_key: "{{ encrypted_dnsmadeeasy_key }}"
        account_secret: "{{ encrypted_dnsmadeeasy_secret }}"
        domain: "theyvoteforyou.org.au"
        record_ttl: 60
        state: present
        record_type: A
        record_name: ec2
        record_value: "{{ inventory_hostname }}"
      tags:
        - dns

    - name: Setup DNS for test.ec2.theyvoteforyou.org.au
      dnsmadeeasy:
        account_key: "{{ encrypted_dnsmadeeasy_key }}"
        account_secret: "{{ encrypted_dnsmadeeasy_secret }}"
        domain: "theyvoteforyou.org.au"
        record_ttl: 60
        state: present
        record_type: CNAME
        record_name: "test.ec2"
        record_value: ec2
      tags:
        - dns

    - name: Get all the DNS records for theyvoteforyou.org.au
      dnsmadeeasy:
        account_key: "{{ encrypted_dnsmadeeasy_key }}"
        account_secret: "{{ encrypted_dnsmadeeasy_secret }}"
        domain: "theyvoteforyou.org.au"
        state: present
      register: response

    - name: Remove any A records for ec2 that we don't want
      dnsmadeeasy:
        account_key: "{{ encrypted_dnsmadeeasy_key }}"
        account_secret: "{{ encrypted_dnsmadeeasy_secret }}"
        domain: "theyvoteforyou.org.au"
        state: absent
        record_type: A
        record_name: ec2
        record_value: "{{ item }}"
      with_items: "{{ response | json_query(query) }}"
      vars:
        query: "result[?type=='A'] | [?name=='ec2'] | [?value!='{{ inventory_hostname }}'].value"
      tags:
        - dns

    - name: Install nginx (for the benefit of certbot)
      apt: pkg=nginx

  vars_files:
    - encrypted_vars/dnsmadeeasy.yml

# This needs to run after the two DNS entries for the hosts are added
# It also needs to be run after nginx has been installed
# And it depends on the deploy user being created
- hosts: tag_Name_theyvoteforyou
  become: true
  vars:
    certbot_auto_renew_user: deploy
    certbot_auto_renew_minute: 10
    certbot_auto_renew_hour: 7
    certbot_create_if_missing: yes
    certbot_certs:
      # TODO: Update the domains that we'll be generating the certificate for
      # In production they should be at least:
      # theyvoteforyou.org.au
      # www.theyvoteforyou.org.au
      # theyvoteforyou.org
      # www.theyvoteforyou.org
      # theyvoteforyou.com.au
      # www.theyvoteforyou.com.au
      - email: contact@oaf.org.au
        domains:
          - ec2.theyvoteforyou.org.au
      # TODO: In production this should be test.theyvoteforyou.org.au
      - email: contact@oaf.org.au
        domains:
          - test.ec2.theyvoteforyou.org.au
    github_users: []
  roles:
    - deploy-user
    - geerlingguy.certbot

# TODO: Don't want to run dns update stuff
- hosts: tag_Name_theyvoteforyou
  become: true
  roles:
    - theyvoteforyou
  vars_files:
    - encrypted_vars/theyvoteforyou.yml
