## FIRST: edit the `vault_identity_list` in ``ansible.cfg``
# and make sure  you have all the password files you need.

## THEN

# Run this like so:
# ansible-playbook site.yml

# To only run this for planningalerts:
# ansible-playbook site.yml -l planningalerts

# To only run this for openaustralia:
# ansible-playbook site.yml -l openaustralia

# To show the value of an encrypted variable:
# ansible planningalerts -m debug -a 'var=mysql_password_production'
# Note that some values are different in development
# ansible development -m debug -a 'var=rds_admin_password'
#
# To encrypt a variable to the default vault id (requires ansible >=2.5.0):
#   ansible-vault encrypt_string --encrypt-vault-id default --name name secret
# To encrypt a variable to the EC2 vault id:
#   ansible-vault encrypt_string --encrypt-vault-id ec2 --name name secret
# See ansible.cfg for notes about which vault id to use.

# Use terraform (see terraform directory) to actually provision ec2 infrastructure

# Ubuntu 16.04 LTS doesn't come with python pre-installed. We need that for
# Ansible to work (for the gather facts). So install python first
- hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: Install Python 3 for Ansible
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
    changed_when: false

  - name: Ensure python3 is available as 'python'
    raw: test -e /usr/bin/python || ln -s /usr/bin/python3 /usr/bin/python
    changed_when: false

- hosts: ec2
  become: true
  tasks:
    - name: Install python3-pip
      apt:
        pkg: python3-pip
        cache_valid_time: 300

    - name: Install boto3 and botocore for AWS operations
      pip:
        name:
          - boto3
          - botocore
        executable: pip3

    - name: Get information about the Mysql 5 instance
      amazon.aws.rds_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        db_instance_identifier: main-database
        region: "{{ ec2_region }}"
      register: rds_mysql5_info
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_mysql' in group_names"

    - name: Set MySQL 5 facts for compatibility
      set_fact:
        rds_mysql5:
          instance:
            endpoint: "{{ rds_mysql5_info.instances[0].endpoint.address }}"
      when: "'requires_mysql' in group_names and rds_mysql5_info.instances | length > 0"

    - name: Get information about the Mysql 8 instance
      amazon.aws.rds_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        db_instance_identifier: maindb
        region: "{{ ec2_region }}"
      register: rds_mysql8_info
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_mysql' in group_names"

    - name: Set MySQL 8 facts for compatibility
      set_fact:
        rds_mysql8:
          instance:
            endpoint: "{{ rds_mysql8_info.instances[0].endpoint.address }}"
      when: "'requires_mysql' in group_names and rds_mysql8_info.instances | length > 0"

    - name: Get information about the postgresql RDS instance
      amazon.aws.rds_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        db_instance_identifier: postgresql
        region: "{{ ec2_region }}"
      register: rds_postgresql_info
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_postgresql' in group_names"

    - name: Set PostgreSQL facts for compatibility
      set_fact:
        rds_postgresql:
          instance:
            endpoint: "{{ rds_postgresql_info.instances[0].endpoint.address }}"
      when: "'requires_postgresql' in group_names and rds_postgresql_info.instances | length > 0"

    - name: Get information about the planningalerts RDS instance
      amazon.aws.rds_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        db_instance_identifier: planningalerts
        region: "{{ ec2_region }}"
      register: rds_planningalerts_info
      # Run this task even when running ansible-playbook with "--check"
      check_mode: false
      when: "'requires_postgresql' in group_names"

    - name: Set PlanningAlerts facts for compatibility
      set_fact:
        rds_planningalerts:
          instance:
            endpoint: "{{ rds_planningalerts_info.instances[0].endpoint.address }}"
      when: "'requires_postgresql' in group_names and rds_planningalerts_info.instances | length > 0"

- hosts: all
  become: true
  roles:
    - base-server

- hosts: mysql
  become: true
  roles:
    - mysql

- hosts: postgresql
  become: true
  roles:
    - postgresql

- hosts: righttoknow
  become: true
  roles:
    - righttoknow

- hosts: planningalerts
  become: true
  roles:
    - planningalerts

- hosts: theyvoteforyou
  become: true
  roles:
    - theyvoteforyou

- hosts: openaustralia
  become: true
  roles:
    - openaustralia

- hosts: proxy
  become: true
  roles:
    - proxy

- hosts: metabase
  become: true
  roles:
    - metabase

- hosts: openvpn
  become: true
  roles:
    - internal/openvpn

- hosts: redis
  become: true
  tasks:
    - name: Install redis
      apt:
        name: redis
    - name: Make redis listen on 0.0.0.0
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "^bind 127.0.0.1"
        line: "bind 0.0.0.0"
      notify:
        - Restart redis
  handlers:
    - name: Restart redis
      service:
        name: redis
        state: restarted
