# Playbook for development VMs on your local box
---

# Ubuntu 16.04 LTS doesn't come with python pre-installed. We need that for
# Ansible to work (for the gather facts). So install python first
- hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: righttoknow
  roles:
    - custom_modules
    - righttoknow
  vars_files:
    - encrypted_vars/righttoknow.yml

- hosts: planningalerts
  roles:
    - custom_modules
    - planningalerts
  vars_files:
    - encrypted_vars/planningalerts.yml

- hosts: electionleaflets
  roles:
    - custom_modules
    - electionleaflets
  vars_files:
    - encrypted_vars/electionleaflets.yml

- hosts: theyvoteforyou
  roles:
    - custom_modules
    - theyvoteforyou
  vars_files:
    - encrypted_vars/theyvoteforyou.yml

- hosts: oaf
  roles:
    - custom_modules
    - oaf

- hosts: openaustralia
  roles:
    - custom_modules
    - openaustralia

- hosts: morph
  roles:
    - custom_modules
    - morph
