# Run this like so:
# ansible-playbook update-ssl-certs.yml

# To only run this for planningalerts:
# ansible-playbook update-ssl-certs.yml -l planningalerts

# To only run this for openaustralia:
# ansible-playbook update-ssl-certs.yml -l openaustralia

- hosts: ec2
  become: true
  tasks:
    - name: Force certificates to be renewed with nginx/apache
      command: certbot renew --non-interactive --force-renew --{{certbot_webserver}}
      when: certbot_webroot is undefined

    - name: Force certificates to be renewed with webroot
      command: certbot renew --non-interactive --force-renew --webroot -w {{ certbot_webroot }}
      when: certbot_webroot is defined
