services:
  plausible:
    ports:
      - 8000:8000

    environment:
      - DATABASE_CACERTFILE

    volumes:
      # TODO: Put this in a better place on the container
      - /srv/www/db.pem:/var/lib/db.pem

    depends_on:
      plausible_db:
        condition: service_completed_successfully

  # We don't need to run postgres locally anymore
  plausible_db:
    entrypoint: ["/bin/true"]
    restart: no
