---
# handlers file for righttoknow
- name: restart varnish
  systemd:
    name: varnish
    daemon_reload: yes
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted
