---
# tasks file for postgresql

- name: Install postgresql server
  apt:
    pkg: postgresql

- name: Update postgresql config to bind to public ip
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/9.5/main
  notify: postgresql restart

- name: Allow all connections from the outside world
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main
  notify: postgresql restart

- name: Install dependency for postgresql_user
  apt: pkg=python-psycopg2

- name: Create admin user
  postgresql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    role_attr_flags: CREATEDB
  become_user: postgres
