---
# tasks file for postgresql

- name: Add postgresql apt repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    filename: pgdg

- name: Import postgresql repository signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    id: ACCC4CF8

# We're currently running 11.8 in production
- name: Install postgresql 11 server
  apt:
    name: "postgresql-11"
    update_cache: true

- name: Update postgresql config to bind to public ip
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/11/main
  notify: postgresql restart

- name: Allow all connections from the outside world
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/11/main
  notify: postgresql restart

- name: Install dependency for postgresql_user
  apt: pkg=python-psycopg2

- name: Create root user
  postgresql_user:
    name: root
    password: "{{ rds_admin_password }}"
    role_attr_flags: CREATEDB,CREATEROLE
  become_user: postgres
