---
# tasks file for roles/internal/mysql

- name: Add key
  apt_key:
    keyserver: pgp.mit.edu
    id: 8C718D3B5072E1F5

# we're installing mysql 5.6 because that's what we're using on AWS
# Install mysql 5.6 on xenial requires a few more jumps than usual because
# the default is 5.7
# Based on https://gist.github.com/Voronenko/31161ab292c7967fcd38c092335a99e1
- name: Add repo for installing mysql 5.6
  apt_repository:
    repo: 'deb http://repo.mysql.com/apt/ubuntu/ wily mysql-5.6'

- name: Make sure that mysql 5.6 server install comes first
  copy:
    src: apt_pin
    dest: /etc/apt/preferences.d/mysql

- name: Install mysql 5.6 server
  apt:
    pkg: mysql-server
    update_cache: yes

- name: Install dependency for following command
  apt: pkg=python-mysqldb

- name: Update mysql config to bind to public ip
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
  notify: mysql restart

- name: Create admin user
  mysql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
