---
# tasks file for roles/internal/mysql

# We're installing mysql 5.7 because that's what we're using on AWS in production
- name: Install mysql 5.7 server
  apt:
    pkg: mysql-server
    update_cache: yes

- name: Install dependency for following command
  apt: pkg=python-mysqldb

- name: Update mysql config to bind to public ip
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
  notify: mysql restart

- name: Create admin user
  mysql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
