---
# tasks file for base-server
- name: Ensure git is installed
  apt:
    pkg: git

# Setup timezone stuff

- name: Install tzdata package
  apt: pkg=tzdata state=present

# We have to do it like this for Ubuntu 16.04
# See https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
- name: Link to correct timezone
  file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    state: link
  notify: Update timezone

# TODO: Install newrelic monitor agent
# See https://rpm.newrelic.com/accounts/154944/servers/get_started

# TODO: Add byobu and enable it by default 
