---
# tasks file for base-server
- name: Enable firewall and deny traffic by default
  ufw:
    state: enabled
    policy: deny

- name: Allow rate-limited SSH trafic
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Allow HTTP traffic
  ufw:
    rule: allow
    port: http
    proto: tcp

- name: Allow HTTPS traffic
  ufw:
    rule: allow
    port: https
    proto: tcp

- name: Ensure git is installed
  apt:
    pkg: git

# Setup timezone stuff

- name: Install tzdata package
  apt: pkg=tzdata state=present

# We have to do it like this for Ubuntu 16.04
# See https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
- name: Link to correct timezone
  file:
    src: /usr/share/zoneinfo/Australia/Sydney
    dest: /etc/localtime
    state: link
  notify: Update timezone
