---
- name: Install dependency for ansible mysql_db module
  apt: pkg=python-mysqldb

- name: Create openaustralia databases
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: "oa-{{ item }}"
  with_items:
    - production
    - staging

- name: Create openaustralia user with access to the database (production)
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: oa-production
    password: "{{ openaustralia_production_mysql_password }}"
    priv: 'oa-production.*:ALL'
    host: "%"

- name: Create openaustralia user with access to the database (staging)
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: oa-staging
    password: "{{ openaustralia_staging_mysql_password }}"
    priv: 'oa-staging.*:ALL'
    host: "%"

# Create fake let's encrypt directories when in development
- name: Create fake let's encrypt directories when in development
  file:
    state: directory
    path: "/etc/letsencrypt/live/{{ item }}"
  with_items:
    - "{{ openaustralia_domain }}"
    - "test.{{ openaustralia_domain }}"
  when: "'development' in group_names"

# We need to setup the SSL certificates before we try to configure nginx
# because otherwise nginx will try to look for non-existent certificates
- name: Copy SSL certificates for development
  copy:
    src: "{{ item }}.pem"
    # We're faking it as if these are let's encrypt certs. Makes for less magic config
    dest: "/etc/letsencrypt/live/{{ item }}/fullchain.pem"
    mode: 0644
  with_items:
    - "{{ openaustralia_domain }}"
    - "test.{{ openaustralia_domain }}"
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: reload apache

- name: Copy SSL keys for development
  copy:
    src: "{{ item }}.key"
    dest: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
    mode: 0640
  with_items:
    - "{{ openaustralia_domain }}"
    - "test.{{ openaustralia_domain }}"
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: reload apache

- name: Install apache now (for the benefit of certbot)
  apt: pkg=apache2
  when: "'ec2' in group_names"

- name: Install certificate using certbot
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_auto_renew_user: deploy
    certbot_auto_renew_minute: 10
    certbot_auto_renew_hour: 7
    certbot_create_if_missing: yes
    certbot_create_standalone_stop_services:
      - apache2
    certbot_certs:
      - email: contact@oaf.org.au
        domains:
          - "{{ openaustralia_domain }}"
          - www."{{ openaustralia_domain }}"
          # TODO: for production include openaustralia.org as well as openaustralia.org.au as well
      - email: contact@oaf.org.au
        domains:
          - "test.{{ openaustralia_domain }}"
          - "www.test.{{ openaustralia_domain }}"
  when: "'ec2' in group_names"

- name: Ensure that directories exist
  file: path={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "/srv/www/production/log"
    - "/srv/www/production/releases"
    - "/srv/www/production/shared/config"
    - "/srv/www/production/shared/images/mps"
    - "/srv/www/production/shared/images/mpsL"
    - "/srv/www/production/shared/searchdb"
    - "/srv/www/staging/log"
    - "/srv/www/staging/releases"
    - "/srv/www/staging/shared/config"
    - "/srv/www/staging/shared/images/mps"
    - "/srv/www/staging/shared/images/mpsL"
    - "/srv/www/staging/shared/searchdb"

# Install php5 on xenial requires a few more jumps than usual
- name: Add repo for installing php5
  apt_repository:
    repo: 'ppa:ondrej/php'

# TODO Extract php-mysql-apache role
- name: Install required packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - php5.6
    - php5.6-curl
    - php5.6-mysql
    - apache2
    - libapache2-mod-php5.6
    - imagemagick
    - libmagickcore-dev
    - libmagickwand-dev
    - ghostscript
    - libxslt1-dev
    - libxml-twig-perl
    - msmtp
    - libdbi-perl
    - libdbd-mysql-perl
    - php5.6-dev
    - libxapian-dev
    - xapian-tools
    - libsearch-xapian-perl

# Matching the version number of libxapian-dev above
- name: Download xapian bindings source
  get_url:
    url: https://oligarchy.co.uk/xapian/1.2.22/xapian-bindings-1.2.22.tar.xz
    dest: /home/deploy
    owner: deploy
    group: deploy
    checksum: sha256:b15ca7984980a1d2aedd3378648ef5f3889cb39a047bac1522a8e5d04f0a8557

- name: Unpack xapian bindings source
  unarchive:
      src: /home/deploy/xapian-bindings-1.2.22.tar.xz
      dest: /home/deploy
      remote_src: yes
      owner: deploy
      group: deploy

- name: Configure xapian bindings
  command: ./configure --with-php
  args:
    chdir: /home/deploy/xapian-bindings-1.2.22
    creates: /home/deploy/xapian-bindings-1.2.22/Makefile
  become_user: deploy

- name: Compile xapian bindings
  command: make
  args:
    chdir: /home/deploy/xapian-bindings-1.2.22
    creates: /home/deploy/xapian-bindings-1.2.22/php/xapian.la
  become_user: deploy

- name: Install xapian bindings
  command: make install
  args:
    chdir: /home/deploy/xapian-bindings-1.2.22
    creates: /usr/lib/php/20131226/xapian.so
  notify: reload apache

- name: Configure php for xapian bindings
  template:
    src: xapian.ini
    dest: /etc/php/5.6/mods-available
  notify: reload apache

- name: Enable xapian for php
  file:
    state: link
    src: /etc/php/5.6/mods-available/xapian.ini
    dest: /etc/php/5.6/apache2/conf.d/30-xapian.ini
  notify: reload apache

# TODO: It would be cleaner if gems were installed as part of the capistrano install
# Then, we could use the Gemfile rather than duplicating this information here
- name: Install required gems
  gem: name={{ item.name }} version={{ item.version }} user_install=no state=present
  with_items:
    - {name: nokogiri,      version: 1.4.4}
    - {name: mini_portile,  version: 0.6.2}
    # It errors when installing mechanize for the first time but does actually end up
    # installing it. So, wondering if we should just ignore errors for mechanize?
    # TODO: Deal with error for mechanize
    - {name: mechanize,     version: 0.9.2}
    - {name: activesupport, version: 3.0.4}
    - {name: builder,       version: 2.1.2}
    - {name: rmagick,       version: 2.15.4}
    - {name: htmlentities,  version: 4.2.1}
    - {name: log4r,         version: 1.1.8}
    - {name: json,          version: 1.8.0}
    - {name: hpricot,       version: 0.6.164}
    - {name: rspec,         version: 2.5.0}
    - {name: rcov,          version: 0.9.9}
    - {name: i18n,          version: 0.5.0}

- name: Enable apache modules
  apache2_module: state=present name={{ item }}
  notify: reload apache
  with_items:
    - expires
    - rewrite
    - ssl

- name: Copy across the php config
  template: src=php.ini dest=/etc/php/5.6/{{ item }}/
  notify: reload apache
  with_items:
    - apache2
    - cli

- name: Copy across the apache configs
  template:
    src: stage.conf
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
  vars:
    stage: "{{ item }}"
    domain: "{{ (item == 'staging') | ternary('test.', '') }}{{ openaustralia_domain }}"
    newrelic_appname: "{{ (item == 'production') | ternary('OpenAustralia.org', 'OpenAustralia.org Staging') }}"
  with_items:
    - production
    - staging
  notify: reload apache

- name: Copy across the apache default config
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/
  notify: reload apache

- name: Copy across the application config
  template:
    src: general
    dest: "/srv/www/{{ item }}/shared"
    owner: deploy
    group: deploy
  vars:
    db_password: "{{ (item == 'production') | ternary(openaustralia_production_mysql_password, openaustralia_staging_mysql_password) }}"
    stage: "{{ item }}"
    domain: "{{ (item == 'staging') | ternary('test.', '') }}{{ openaustralia_domain }}"
  with_items:
    - production
    - staging
  notify: reload apache

- name: Copy across the parser config
  template:
    src: parser_configuration.yml
    dest: "/srv/www/{{ item }}/shared"
    owner: deploy
    group: deploy
  vars:
    stage: "{{ item }}"
  with_items:
    - production
    - staging

- name: Enable virtual hosts
  file:
    src: /etc/apache2/sites-available/{{ item }}.conf
    dest: /etc/apache2/sites-enabled/{{ item }}.conf
    state: link
  with_items:
    - production
    - staging
    - 000-default
  notify: reload apache

- name: Copy msmtp configuration
  template: src=msmtprc dest=/etc/

# daily update at night for MP data (regmem, data from Public Whip etc.)
- name: Set up cron job for daily update
  cron:
    name: "dailyupdate {{ item }}"
    user: deploy
    hour: 1
    minute: 37
    job: "/srv/www/{{ item }}/current/twfy/scripts/dailyupdate"
    state: "{{ openaustralia_cron_enabled | ternary('present', 'absent')}}"
  with_items:
    - production
    - staging

# every week early Sunday grab weekly range of data
- name: Set up cron job for weekly update
  cron:
    name: "weeklyupdate {{ item }}"
    user: deploy
    hour: 4
    minute: 23
    weekday: 0
    job: "/srv/www/{{ item }}/current/twfy/scripts/weeklyupdate"
    state: "{{ openaustralia_cron_enabled | ternary('present', 'absent')}}"
  with_items:
    - production
    - staging

# TODO: not sure of the path here
# Email updates (Going at 10am to give me time to fix things if necessary)
- name: Set up cron job for email alerts
  cron:
    name: "alertmailer {{ item }}"
    user: deploy
    hour: 10
    minute: 0
    weekday: "1-5"
    job: "php -q /srv/www/{{ item }}/current/twfy/scripts/alertmailer.php"
    state: "{{ openaustralia_cron_enabled | ternary('present', 'absent')}}"
  with_items:
    - production
    - staging

# Morning update (Australian Hansard is supposed to be up by 9am the next working day)
- name: Set up cron job for morning updates
  cron:
    name: "morningupdate {{ item }}"
    user: deploy
    hour: 9
    minute: 5
    weekday: "1-5"
    job: "VERBOSE=true /srv/www/{{ item }}/current/twfy/scripts/morningupdate"
    state: "{{ openaustralia_cron_enabled | ternary('present', 'absent')}}"
  with_items:
    - production
    - staging

# TODO: Do I need to make sure a MTA is installed for this to work?

# For development just make the output of cron get mailed to me
# TODO: Setup MAILTO to go to web-administrators@openaustralia.org and common slack channel for production
- cronvar:
    name: MAILTO
    user: deploy
    value: matthew@oaf.org.au

# For cross-domain redirects it would be good if we could do those at cloudflare.
# Otherwise, we should probably have a "redirect" role which handles cross-domain
# redirects for all domains

# TODO: Add data.openaustralia.org.au
# TODO: I have faint memory of rsync service for data.openaustralia.org.au
# TODO: Add redirects for software.openaustralia.org.au?
# TODO: Add backups for member images, xml files, cached downloads, register of member's interests
# TODO: Install newrelic for php
# TODO: Add password to staging site
