---
- name: Ensure that we have the Docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Ensure that we have the docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"

- name: Install docker and docker compose
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: git checkout plausible-ce
  ansible.builtin.git:
    repo: "https://github.com/plausible/community-edition"
    version: v2.1.4
    depth: 1
    dest: /srv/www

- name: Install dependency for postgresql_db
  apt:
    pkg: python3-psycopg2

- name: Create database
  postgresql_db:
    login_host: "{{ postgresql_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    name: "plausible"

- name: Create posgresql role
  postgresql_user:
    login_host: "{{ postgresql_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    db: "plausible"
    name: "plausible"
    password: "{{ db_password }}"
    no_password_changes: true

- name: "Give plausible role access to the database"
  postgresql_privs:
    login_host: "{{ postgresql_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    db: "plausible"
    roles: "plausible"
    privs: ALL
    type: database

- name: Copy across .env
  template:
    src: env
    dest: /srv/www/.env

- name: Copy across compose.override.yml
  template:
    src: compose.override.yml
    dest: /srv/www/

# Requires: ansible-galaxy collection install "community.docker:<4.0.0"
# Commented out for the time being because it's not working with this
# ancient version of ansible
# TODO: Fix this
# For this to work we had to upgrade from ansible 2.9.x to 2.10.x. However this
# change is untested for every role other than "plausible". Ugh.
- name: Run plausible
  community.docker.docker_compose_v2:
    project_src: /srv/www

# TODO: Connect to RDS postgres rather than its own
# TODO: Add backups for databases
# TODO: Add email configuration
