---

- name: Include Debian installation tasks
  include_tasks: install.deb.yml
  when: ansible_os_family == "Debian" and not backup_remove

- name: Include RedHat installation tasks
  include_tasks: install.red.yml
  when: ansible_os_family == "RedHat" and not backup_remove

- name: Include configuration tasks
  include_tasks: configure.yml
  when: not backup_remove

- name: Include removal tasks
  include_tasks: remove.yml
  when: backup_remove
