---
galaxy_info:
  author: your name
  description:
  company: your company (optional)
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  #platforms:
  #- name: EL
  #  versions:
  #  - all
  #  - 5
  #  - 6
  #  - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #- name: SmartOS
  #  versions:
  #  - all
  #  - any
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: Amazon
  #  versions:
  #  - all
  #  - 2013.03
  #  - 2013.09
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  #- name: Ubuntu
  #  versions:
  #  - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
  #  - trusty
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  #- name: Debian
  #  versions:
  #  - all
  #  - etch
  #  - lenny
  #  - squeeze
  #  - wheezy
  #
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
  #categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
  #- development
  #- monitoring
  #- networking
  #- packaging
  #- system
  #- web
dependencies:
  - role: base-server
  - role: rvm_io.ruby
    rvm1_rubies:
      # Picking similar one installed on the old server (and used by openaustralia.org)
      - ruby-1.8.7-p374
    rvm1_install_flags: '--auto-dotfiles'      # Remove --user-install from defaults
    rvm1_install_path: /usr/local/rvm          # Set to system location
    rvm1_user: root                            # Need root account to access system location
    # Increase timeout on curl. For some reason some requests are taking too long
    rvm1_ruby_install_flags: "--max-time 20"
    # Don't want us updating rvm on every run by default
    # rvm1_rvm_check_for_updates: false
    # Use round-robin pool of gpg key servers to avoid timeout
    rvm1_gpg_key_server: 'hkp://pool.sks-keyservers.net'
  - role: Stouts.backup
    backup_gpg_pw: "{{ backup_gpg_pw }}"
    backup_max_age: 6M
    backup_profiles:
      - name: openaustralia_data
        schedule: 0 2 * * *
        source: /data
        # TODO: Duplicity will be very confused if two different machines from the same stage try to backup
        target: "s3://s3.amazonaws.com/oaf-backups/openaustralia/{{ inventory_hostname }}/data"
