---
dependencies:
  - role: base-server
  - role: ANXS.mysql
    mysql_bind_address: '127.0.0.1'
    mysql_root_password: ''
    mysql_databases:
      - name: theyvoteforyou
  - role: abtris.nginx-passenger
  - role: rvm_io.ruby
    # TODO: How do we get it to use what's in the .ruby-version file?
    rvm1_rubies:
      - ruby-2.3.1
    rvm1_install_flags: '--auto-dotfiles'      # Remove --user-install from defaults
    rvm1_install_path: /usr/local/rvm          # Set to system location
    rvm1_user: root                            # Need root account to access system location
    # Use round-robin pool of gpg key servers to avoid timeout
    rvm1_gpg_key_server: 'hkp://pool.sks-keyservers.net'
  - role: nickhammond.logrotate
    logrotate_scripts:
      - name: rails
        path: "/srv/www/shared/log/*.log"
        options:
          - daily
          - rotate 30
          - compress
          - missingok
          - copytruncate
  - role: azavea.elasticsearch
    elasticsearch_bind_host: 127.0.0.1
    java_version: "8u151*"
  - role: Stouts.backup
    backup_gpg_pw: "{{ theyvoteforyou_backup_gpg_pw }}"
    backup_target_user: "{{ theyvoteforyou_backup_target_user }}"
    backup_target_pass: "{{ theyvoteforyou_backup_target_pass }}"
    backup_max_age: 6M
    backup_profiles:
      - name: automysqlbackup
        schedule: 0 4 * * *
        source: /var/lib/automysqlbackup
        # TODO: Duplicity will be very confused if two different machines from the same stage try to backup
        target: "s3://s3.amazonaws.com/oaf-backups/theyvoteforyou/{{ inventory_hostname }}"
