---
# tasks file for roles/internal/theyvoteforyou-mysql

- name: Install mysql server
  apt: pkg=mysql-server

- name: Install dependency for following command
  apt: pkg=python-mysqldb

- name: Update mysql config to bind to public ip
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
  notify: mysql restart

- name: Create admin user
  mysql_user:
    name: admin
    password: "{{ rds_admin_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
