---

- name: Check if CloudWatch is already installed
  stat:
    path: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent
  register: cloudwatch_installed

- name: Create CloudWatch temporary directory
  tempfile:
    state: directory
    suffix: awscwa
  register: awscwa

- name: Download CloudWatch agent
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
    dest: "{{ awscwa.path }}"
    # This is the checksum for the particular version that is the latest at the time
    # This will need to be updated if the agent gets updated
    checksum: sha256:3eca0063adb3b402841d40571f4bba1b5008ca07a9a7df536fd25bed8e0b0681
  # when: "'ec2' in group_names and cloudwatch_installed.stat.exists == False"
  when: "'ec2' in group_names"

- name: Install CloudWatch agent
  shell: "dpkg -i -E ./amazon-cloudwatch-agent.deb"
  args:
    chdir: "{{ awscwa.path }}"
    creates: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent
  when: "'ec2' in group_names"
  # when: "'ec2' in group_names and cloudwatch_installed.stat.exists == False"

- name: Configure CloudWatch
  template:
    src: config.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
  when: "'ec2' in group_names"
  notify:
    - restart CloudWatch Agent

- name: Configure CloudWatch service
  service:
    name: amazon-cloudwatch-agent
    enabled: yes
    state: started
  when: "'ec2' in group_names"
