---
- name: Install dependency for following command
  apt: pkg=python-mysqldb

- name: Create theyvoteforyou databases
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: "tvfy-{{ item }}"
  with_items:
    - production
    - staging

- name: Create theyvoteforyou user with access to the database (production)
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: tvfy-production
    password: "{{ theyvoteforyou_production_mysql_password }}"
    priv: 'tvfy-production.*:ALL'
    host: "%"

- name: Create theyvoteforyou user with access to the database (staging)
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: tvfy-staging
    password: "{{ theyvoteforyou_staging_mysql_password }}"
    priv: 'tvfy-staging.*:ALL'
    host: "%"

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: '{{item}}'
  with_items:
    - /srv/www
    - /srv/www/production
    - /srv/www/production/shared
    - /srv/www/staging
    - /srv/www/staging/shared

- name: Copy application settings
  copy:
    src: settings.yml
    dest: "/srv/www/{{ item }}/shared/config/"
    owner: deploy
    group: deploy
  with_items:
    - production
    - staging
  notify: nginx reload

- name: Copy application database configuration
  template:
    src: "database-{{ item }}.yml"
    dest: "/srv/www/{{ item }}/shared/config/database.yml"
    owner: deploy
    group: deploy
  with_items:
    - production
    - staging
  notify: nginx reload

- name: Copy application secrets
  template:
    src: secrets.yml
    dest: "/srv/www/{{ item }}/shared/config/"
    owner: deploy
    group: deploy
  with_items:
    - production
    - staging
  notify: nginx reload

- name: Copy application newrelic configuration
  template:
    src: newrelic.yml
    dest: "/srv/www/{{ item }}/shared/config/"
    owner: deploy
    group: deploy
  with_items:
    - production
    - staging
  notify: nginx reload

- name: Ensure packages to build gem native extensions are installed
  apt:
    pkg: "{{item}}"
  with_items:
    - libmysqlclient-dev

- name: Copy SSL certificates for development
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/
    mode: 0644
  with_items:
    - theyvoteforyou.org.au.dev.pem
    - test.theyvoteforyou.org.au.dev.pem
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: nginx reload

- name: Copy SSL keys for development
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/private/
    group: ssl-cert
    mode: 0640
  with_items:
    - theyvoteforyou.org.au.dev.key
    - test.theyvoteforyou.org.au.dev.key
  # Only run this task when this machine is the development group
  when: "'development' in group_names"
  notify: nginx reload

- name: Copy test/test password for staging site
  copy:
    src: htpasswd
    dest: /etc/nginx/
  notify: nginx restart

- name: Copy nginx main configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/
  notify: nginx restart

- name: Copy nginx site configuration
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/
  with_items:
    - default
    - production
    - staging
  notify: nginx reload

- name: Enable sites
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  with_items:
    - default
    - production
    - staging
  notify: nginx reload

- name: Allow deploy user to control application services
  copy:
    src: theyvoteforyou_foreman
    dest: /etc/sudoers.d/
    validate: visudo -cf %s
  # notify: sudo reload

- name: Set up daily load cron job
  cron:
    name: theyvoteforyou_application_load_daily
    user: deploy
    hour: 9
    minute: 15
    weekday: 1-5
    job: "cd /srv/www/production/current && /usr/local/bin/bundle exec rake application:load:daily RAILS_ENV=production"
  when: theyvoteforyou_cron_enabled
