---
- name: Install memcached
  apt:
    pkg: memcached

- name: Make memcached listen to the outside world
  lineinfile:
    path: /etc/memcached.conf
    regexp: "^-l 127.0.0.1"
    line: "-l 0.0.0.0"
  notify:
    - memchached restart

- include_tasks: database.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: "{{item}}"
  with_items:
    - /srv/www/production
    - /srv/www/production/shared
    - /srv/www/production/shared/config
    - /srv/www/production/shared/config/credentials
    - /srv/www/production/shared/log
    - /srv/www/production/shared/public
    - /srv/www/production/shared/system

- name: Ensure packages to build gem native extensions are installed
  apt:
    pkg:
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      # Needed for rgeo geos support. See https://github.com/rgeo/rgeo/issues/227#issuecomment-1145169888
      - libgeos++-dev
      - libgeos-dev

- name: Copy rails master key for production
  template:
    src: "production.key"
    dest: "/srv/www/production/shared/config/credentials/production.key"
    owner: deploy
    group: deploy

- name: Allow deploy user to control services
  copy:
    src: deploy_service_control
    dest: /etc/sudoers.d/
    validate: visudo -cf %s

- name: Install postfix to handle incoming email
  apt:
    pkg: postfix

- name: Update postfix configuration
  template:
    src: "{{ item }}"
    dest: /etc/postfix
  with_items:
    - transport
    - virtual_alias
  notify: restart postfix

- name: Install script to handle incoming email
  template:
    src: incoming-email.sh
    dest: /usr/local/bin
    # Make it executable
    mode: 0755

# Crude way of running postconf below. Will always change things and not
# restart postfix when needed

- name: Set postfix pipe handler
  command: postconf -M -e "planningalerts/unix=planningalerts unix - n n - 50 pipe flags=R user=deploy directory=/srv/www/production/current argv=/usr/local/bin/incoming-email.sh"

- name: Set postfix virtual alias
  command:  postconf -e "virtual_alias_maps=regexp:/etc/postfix/virtual_alias"

- name: Set postfix transport maps
  command: postconf -e "transport_maps=regexp:/etc/postfix/transport"

- name: Set postfix destination
  command: postconf -e "mydestination=planningalerts.org.au"
