---
- name: Install memcached
  apt:
    pkg: memcached

- name: Make memcached listen to the outside world
  lineinfile:
    path: /etc/memcached.conf
    regexp: "^-l 127.0.0.1"
    line: "-l 0.0.0.0"
  notify:
    - memchached restart

- include_tasks: database.yml

- name: Ensure that deploy owns /srv/www and /srv/www/shared
  file:
    state: directory
    owner: deploy
    group: deploy
    path: "{{item}}"
  with_items:
    - /srv/www/production
    - /srv/www/production/shared
    - /srv/www/production/shared/config
    - /srv/www/production/shared/config/credentials
    - /srv/www/production/shared/log
    - /srv/www/production/shared/public
    - /srv/www/production/shared/system

- name: Ensure packages to build gem native extensions are installed
  apt:
    pkg:
      - libmysqlclient-dev
      - libxml2-dev
      - libxslt1-dev

- name: Copy rails master key for production
  template:
    src: "production.key"
    dest: "/srv/www/production/shared/config/credentials/production.key"
    owner: deploy
    group: deploy

- name: Allow deploy user to control services
  copy:
    src: deploy_service_control
    dest: /etc/sudoers.d/
    validate: visudo -cf %s
