---
# handlers file for planningalerts
- name: restart web server
  # This also restarts the background queue but we can live that
  service:
    name: "planningalerts-{{ item }}.target"
    state: restarted
  with_items:
    - production
    - staging

- name: memchached restart
  service:
    name: memcached
    state: restarted