---
# These are plugins that we want installed and enabled.
wordpress_plugins:
  - advanced-edit-cforms
  - akismet
  - better-rss-widget
  - broken-link-checker
  # cforms2 gives a different version of the plugin than is currently installed on oaf.org.au
  - cforms2
  - check-email
  # CiviCRM needs to be installed differently
  - collapsing-archives
  - google-analytics-for-wordpress
  # Hello Dolly is already installed
  - hifi
  - mailchimp-for-wp
  - nivo-slider-light
  - quotes-collection
  - recent-posts-embed
  - scalable-vector-graphics-svg
  - subscribe-to-comments
  - tagaroo
  # twitter-tracker appears to be a different version than on oaf.org.au
  - twitter-tracker
  - twitter-widget-pro
  - typekit-fonts-for-wordpress
  - update-notifier
  - widget-context
  - widget-logic
  - wordpress-https
  - wordpress-importer
  - wp-twittersearch
  - wp-hide-pages
  - wp-super-cache
