---
dependencies:
  - role: deploy-user
  - role: MichaelRigart.aliases
    aliases_list:
      - {user: deploy, alias: root}
      - {user: root, alias: web-administrators@openaustralia.org}
  - role: ANXS.ntp
    # ietf has stopped providing the leap seconds file
    ntp_leapurl: https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list
  - role: jnv.unattended-upgrades
    unattended_automatic_reboot: true
  - role: awscloudwatch
  - role: newrelic.newrelic-infra
    nrinfragent_config:
      license_key: "{{ newrelic_license_key }}"
      display_name: "{{ name }}"
