---
dependencies:
  - role: deploy-user
    github_users: ['mlandauer', 'henare']
  - role: MichaelRigart.aliases
    aliases_list:
      - {user: deploy, alias: root}
      - {user: root, alias: web-administrators@openaustralia.org}
  - role: ANXS.ntp
  - role: jnv.unattended-upgrades
    unattended_automatic_reboot: true
