---
- name: Install dependency for ansible mysql_db module
  apt:
    pkg: python-mysqldb

# TODO: Do we want a staging setup too?
- name: Create database
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: "{{ item }}-production"
  with_items:
    - oaf
    - civi

- name: Create civi user with access to the database
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: civi-production
    password: "{{ civicrm_production_mysql_password }}"
    priv: 'civi-production.*:ALL'
    host: "%"

- name: Create oaf user with access to the database
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: oaf-production
    password: "{{ oaf_production_mysql_password }}"
    priv: 'oaf-production.*:ALL'
    host: "%"

# Install php5 on xenial requires a few more jumps than usual
- name: Add repo for installing php5
  apt_repository:
    repo: 'ppa:ondrej/php'

# We're using php 5.6 as that's the latest php supported by the
# version of civicrm currently running in production
# TODO: Check latest packages required by civicrm
# TODO: Check those required by wordpress
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - php5.6-mysql
    - php5.6-curl
    - apache2
    - libapache2-mod-php5.6
    - mysql-client
    # TODO We'll need mod rewrite I think
  notify: reload apache

- name: Remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Set permissions
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    state: directory

# TODO: See if there is another more sensible way we could install this
- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "/usr/local/bin/wp-cli"
    mode: 0755

- name: download wordpress
  shell: "wp-cli --path='/var/www/html' core download"
  args:
    creates: /var/www/html/index.php
  become_user: www-data

- name: configure wordpress
  shell: "wp-cli --path='/var/www/html' core config --dbname=oaf-production --dbuser=oaf-production --dbpass={{ oaf_production_mysql_password }} --dbhost={{ mysql_host }}"
  args:
    creates: /var/www/html/wp-config.php
  become_user: www-data

# TODO: Is there a creates in this situation?
- name: install wordpress
  shell: "wp-cli --path='/var/www/html' core install --url=http://oaf.org.au.test --title='OpenAustralia Foundation' --admin_user={{ admin_user }} --admin_password={{ admin_password }} --admin_email=contact@oaf.org.au"
  become_user: www-data

# TODO: Check latest list of plugins against production
- name: Install wordpress plugins
  shell: "wp-cli --path='/var/www/html' plugin install {{ item }}"
  args:
    creates: /var/www/html/wp-content/plugins/{{ item }}
  become_user: www-data
  with_items:
    - advanced-edit-cforms
    - akismet
    - better-rss-widget
    - broken-link-checker
    # cforms2 gives a different version of the plugin than is currently installed on oaf.org.au
    - cforms2
    # CiviCRM I think needs to be installed differently
    - collapsing-archives
    - dynamic-content-gallery-plugin
    - easy-wp-smtp
    - google-analytics-for-wordpress
    # Hello Dolly is already installed
    - hifi
    - mailchimp-for-wp
    - nivo-slider-light
    - quotes-collection
    - recent-posts-embed
    - redirection
    - scalable-vector-graphics-svg
    - sociable
    - subscribe-to-comments
    - tagaroo
    # twitter-tracker appears to be a different version than on oaf.org.au
    - twitter-tracker
    - twitter-widget-pro
    - typekit-fonts-for-wordpress
    - update-notifier
    - w3-total-cache
    - widget-context
    - widget-logic
    - wordpress-https
    - wordpress-importer
    - wp-twittersearch
    - wp-hide-pages
    - wp-super-cache

# TODO: Maybe worth looking at the wp-cli civicrm integration for installing civicrm?
# - name: download civicrm
#   get_url:
#     url: https://download.civicrm.org/civicrm-4.6.36-wordpress.zip
#     dest: /tmp/civicrm-wordpress.zip
#
# - name: Install zip to handle download
#   apt:
#     name: zip
#     state: present
#
# - name: install civicrm
#   unarchive:
#     src: /tmp/civicrm-wordpress.zip
#     dest: /var/www/html/wp-content/plugins
#     owner: www-data
#     group: www-data
#     copy: no
#
# - name: Fix up civicrm plugin directory permissions
#   file:
#     path: /var/www/html/wp-content/plugins/civicrm
#     owner: www-data
#     group: www-data
#     state: directory
#     recurse: yes
#
# - name: Create civicrm files directory
#   file:
#     path: /var/www/html/wp-content/plugins/files
#     owner: www-data
#     group: www-data
#     state: directory

- name: Apache config
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available
  notify: reload apache

# TODO: How does civicrm know its database credentials?
# TODO: How are the oaf templates installed?
# TODO: Use new certificates method
# TODO: Add certificates in production
# TODO: Ensure that we're handling the alternative domain names
# TODO: Create data directory
