---
- include_vars: encrypted.yml

# TODO Extract php-mysql-apache role
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - php5-mysql
    - php5-curl
    - apache2
    - libapache2-mod-php5
    # TODO We'll need mod rewrite I think
  notify: reload apache

- name: Remove default index.html
  file: path=/var/www/html/index.html state=absent

- name: Set permissions
  file: path=/var/www/html owner=www-data group=www-data state=directory

- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "/usr/local/bin/wp-cli"
    mode: 0755

- name: download wordpress
  shell: "wp-cli --path='/var/www/html' core download"
  args:
    creates: /var/www/html/index.php
  become_user: www-data

- name: configure wordpress
  shell: "wp-cli --path='/var/www/html' core config --dbname=wordpress --dbuser=root"
  args:
    creates: /var/www/html/wp-config.php
  become_user: www-data

- name: install wordpress
  shell: "wp-cli --path='/var/www/html' core install --url=http://oaf.org.au.dev --title='OpenAustralia Foundation' --admin_user={{ admin_user }} --admin_password={{ admin_password }} --admin_email=contact@oaf.org.au"
  become_user: www-data

- name: Install wordpress plugins
  shell: "wp-cli --path='/var/www/html' plugin install {{ item }}"
  args:
    creates: /var/www/html/wp-content/plugins/{{ item }}
  become_user: www-data
  with_items:
    - advanced-edit-cforms
    - akismet
    - better-rss-widget
    - broken-link-checker
    # cforms2 gives a different version of the plugin than is currently installed on oaf.org.au
    - cforms2
    # CiviCRM I think needs to be installed differently
    - collapsing-archives
    - dynamic-content-gallery-plugin
    - easy-wp-smtp
    - google-analytics-for-wordpress
    # Hello Dolly is already installed
    - hifi
    - mailchimp-for-wp
    - nivo-slider-light
    - quotes-collection
    - recent-posts-embed
    - redirection
    - scalable-vector-graphics-svg
    - sociable
    - subscribe-to-comments
    - tagaroo
    # twitter-tracker appears to be a different version than on oaf.org.au
    - twitter-tracker
    - twitter-widget-pro
    - typekit-fonts-for-wordpress
    - update-notifier
    - w3-total-cache
    - widget-context
    - widget-logic
    - wordpress-https
    - wordpress-importer
    - wp-twittersearch
    - wp-hide-pages
    - wp-super-cache

- name: download civicrm
  get_url: url=http://sourceforge.net/projects/civicrm/files/civicrm-stable/4.5.8/civicrm-4.5.8-wordpress.zip dest=/tmp/civicrm-4.5.8-wordpress.zip

- name: Install zip to handle download
  apt: name=zip state=present

- name: install civicrm
  unarchive: src=/tmp/civicrm-4.5.8-wordpress.zip dest=/var/www/html/wp-content/plugins owner=www-data group=www-data copy=no

- name: Fix up civicrm plugin directory permissions
  file: path=/var/www/html/wp-content/plugins/civicrm owner=www-data group=www-data state=directory recurse=yes

- name: Create civicrm files directory
  file: path=/var/www/html/wp-content/plugins/files owner=www-data group=www-data state=directory

- name: Apache config
  template: src=000-default.conf dest=/etc/apache2/sites-available
  notify: reload apache
