---
- name: Install dependency for ansible mysql_db module
  apt:
    pkg: python-mysqldb

# TODO: Do we want a staging setup too?
- name: Create oaf database
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: oaf-production

- name: Create oaf user with access to the database
  mysql_user:
    login_host: "{{ mysql_host }}"
    login_user: admin
    login_password: "{{ rds_admin_password }}"
    name: oaf-production
    password: "{{ oaf_production_mysql_password }}"
    priv: 'oaf-production.*:ALL'
    host: "%"

# Install php 7.4 on bionic requires a few more jumps than usual
- name: Add repo for installing php 7.4
  apt_repository:
    repo: 'ppa:ondrej/php'

# We're using php 7.4 as it's the minimum required for recent Wordpress
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - php7.4-mysql
    - php7.4-curl
    - php7.4-xml
    - php7.4-zip
    - php7.4-mbstring
    - php7.4-gd
    - php7.4-imagick
    - apache2
    - libapache2-mod-php7.4
    - mysql-client
  notify: reload apache

- name: Enable apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - ssl
  notify: reload apache

- name: Remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Set permissions
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    state: directory

# TODO: See if there is another more sensible way we could install this
- name: install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "/usr/local/bin/wp-cli"
    mode: 0755

- name: download wordpress
  shell: "wp-cli --path='/var/www/html' core download"
  args:
    creates: /var/www/html/index.php
  become_user: www-data

- name: configure wordpress
  shell: "wp-cli --path='/var/www/html' core config --dbname=oaf-production --dbuser=oaf-production --dbpass={{ oaf_production_mysql_password }} --dbhost={{ mysql_host }}"
  args:
    creates: /var/www/html/wp-config.php
  become_user: www-data

# TODO: Is there a creates in this situation?
- name: install wordpress
  shell: "wp-cli --path='/var/www/html' core install --url=https://www.{{ oaf_domain }} --title='OpenAustralia Foundation' --admin_user={{ admin_user }} --admin_password={{ admin_password }} --admin_email=contact@oaf.org.au --skip-email"
  become_user: www-data

# Update the password of the admin user because the above task doesn't seem to work as expected
- name: update wordpress admin password
  shell: "wp-cli --path='/var/www/html' user update admin --skip-email --user_pass={{ admin_password }}"
  become_user: www-data

- name: Install wordpress plugins
  shell: "wp-cli --path='/var/www/html' plugin install --activate {{ item }}"
  args:
    creates: /var/www/html/wp-content/plugins/{{ item }}
  become_user: www-data
  with_items:
    - akismet
    - better-rss-widget
    - broken-link-checker
    - check-email
    - collapsing-archives
    - google-analytics-for-wordpress
    - hifi
    - mailchimp-for-wp
    - advanced-gutenberg
    - quotes-collection
    - scalable-vector-graphics-svg
    - subscribe-to-comments
    - tagaroo
    - twitter-widget-pro
    - typekit-fonts-for-wordpress
    - update-notifier
    - vaultpress
    - widget-context
    - widget-logic
    - wordfence
    - wordpress-importer
    - wp-twittersearch
    - wp-hide-pages
    - wp-super-cache
    # TODO: What is advanced-cached.php ?

# Remove plugins that are installed by default but not needed
- name: Remove wordpress plugins
  shell: "wp-cli --path='/var/www/html' plugin delete {{ item }}"
  become_user: www-data
  with_items:
    - hello

# creates has a different form so we're doing this separately from above
- name: Install wordpress plugins
  shell: "wp-cli --path='/var/www/html' plugin install --activate https://github.com/afragen/github-updater/archive/master.zip"
  args:
    creates: /var/www/html/wp-content/plugins/github-updater
  become_user: www-data

# This theme is required by the openaustralia foundation theme
- name: Install thematic theme
  shell: "wp-cli --path='/var/www/html' theme install --url https://github.com/openaustralia/thematic/archive/refs/heads/1.0.4-php7.4-compat.zip https://github.com/openaustralia/Thematic/archive/refs/heads/1.0.4-php7.4-compat.zip"
  args:
    creates: /var/www/html/wp-content/themes/thematic/
  become_user: www-data

# This theme is dependent on there being a font called "museo-slab".
# We're using typekit to provide that font. The typekit plugin needs
# to point at a typekit kit that has the museo-slab font installed.
# Updates to the theme are handled by the GitHub updater plugin
- name: Install openaustralia foundation theme
  # Installs the latest on the master branch
  shell: "wp-cli --path='/var/www/html' theme install https://github.com/openaustralia/oaf-thematic/archive/master.zip --activate"
  args:
    creates: /var/www/html/wp-content/themes/oaf-thematic/
  become_user: www-data

- name: Get current domain in database
  shell: "wp-cli --path=/var/www/html option get siteurl"
  become_user: www-data
  register: siteurl_contents

# TODO: Do we always want to convert urls to https?
- name: Convert domains in database
  shell: "wp-cli --path=/var/www/html search-replace {{ item }}://{{ current_siteurl }} {{ item }}://{{ new_siteurl }}"
  become_user: www-data
  vars:
    current_siteurl: "{{ siteurl_contents.stdout | urlsplit('hostname') }}"
    new_siteurl: "www.{{ oaf_domain }}"
  when: current_siteurl != new_siteurl
  with_items:
    - http
    - https

- name: Apache config
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available
  notify: reload apache

- import_tasks: certificates.yml

# Normally this file is put in place by Wordpress itself when you change the
# setting on the permalinks. But doing it here so things should work out of
# the box
- name: htaccess rewrites for pretty urls
  template:
    src: htaccess
    dest: /var/www/html/.htaccess
  notify: reload apache

# Despite the name apparently this version of newrelic monitor also supports php 7.
# See: https://discuss.newrelic.com/t/where-to-download-php7-agent/35807
- name: Uninstall newrelic php monitor
  apt:
    pkg: newrelic-php5
    state: absent

- name: Remove configuration for newrelic php monitor
  file:
    state: absent
    path: /etc/php/5.6/mods-available/newrelic.ini
  notify: reload apache

- name: display post install message
  debug:
    msg:
      - 'Now go to https://www.{{ oaf_domain }}/wp-admin'
      - 'You will need to login with:'
      - '  Username: {{ admin_user }}'
      - '  Password: {{ admin_password }}'

# TODO: Add newrelic application monitoring
# TODO: Mail sent to www-data needs to go to root (or switch over to deploy user)

- name: Autoremove unneeded packages
  apt:
    autoremove: yes
