---
- name: Install dependency for postgresql_db
  apt:
    pkg: python3-psycopg2

- name: Download Docker repository signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.asc
    mode: '0644'

- name: Add Docker apt repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: /usr/share/keyrings/docker-archive-keyring.asc
    state: present

- name: Install docker
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io

- name: Install dependency for ansible mysql_db module
  apt:
    pkg: python3-mysqldb

- name: Install pip
  apt:
    pkg: python3-pip

- name: Install docker-compose python library
  pip:
    name: docker-compose

- name: Create database
  postgresql_db:
    login_host: "{{ postgresql_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    name: "metabase"

- name: Create posgresql role
  postgresql_user:
    login_host: "{{ postgresql_host }}"
    login_user: root
    login_password: "{{ rds_admin_password }}"
    db: "metabase"
    name: "metabase"
    password: "{{ db_password }}"
    priv: ALL

- name: Create /srv/www directory
  file:
    state: directory
    owner: deploy
    group: deploy
    path: /srv/www

- name: Copy across docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /srv/www

- name: Run metabase
  docker_compose:
    project_src: /srv/www
